/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ObjectivesRouteImport } from './routes/objectives'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsIndexRouteImport } from './routes/subjects.index'
import { Route as ReviewIndexRouteImport } from './routes/review.index'
import { Route as ObjectivesIndexRouteImport } from './routes/objectives.index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as SubjectsSlugRouteImport } from './routes/subjects.$slug'
import { Route as ReviewCaseIdRouteImport } from './routes/review.$caseId'
import { Route as ObjectivesSlugRouteImport } from './routes/objectives.$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as GuidesSlugIndexRouteImport } from './routes/guides/$slug/index'
import { Route as GuidesSlugWalkthroughRouteImport } from './routes/guides/$slug/walkthrough'

const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectivesRoute = ObjectivesRouteImport.update({
  id: '/objectives',
  path: '/objectives',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubjectsRoute,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewRoute,
} as any)
const ObjectivesIndexRoute = ObjectivesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ObjectivesRoute,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSlugRoute = SubjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SubjectsRoute,
} as any)
const ReviewCaseIdRoute = ReviewCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => ReviewRoute,
} as any)
const ObjectivesSlugRoute = ObjectivesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ObjectivesRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugIndexRoute = GuidesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuidesSlugRoute,
} as any)
const GuidesSlugWalkthroughRoute = GuidesSlugWalkthroughRouteImport.update({
  id: '/walkthrough',
  path: '/walkthrough',
  getParentRoute: () => GuidesSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/contribute': typeof ContributeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/objectives': typeof ObjectivesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRouteWithChildren
  '/subjects': typeof SubjectsRouteWithChildren
  '/guides/$slug': typeof GuidesSlugRouteWithChildren
  '/objectives/$slug': typeof ObjectivesSlugRoute
  '/review/$caseId': typeof ReviewCaseIdRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
  '/guides/': typeof GuidesIndexRoute
  '/objectives/': typeof ObjectivesIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/guides/$slug/walkthrough': typeof GuidesSlugWalkthroughRoute
  '/guides/$slug/': typeof GuidesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/contribute': typeof ContributeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/objectives/$slug': typeof ObjectivesSlugRoute
  '/review/$caseId': typeof ReviewCaseIdRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
  '/guides': typeof GuidesIndexRoute
  '/objectives': typeof ObjectivesIndexRoute
  '/review': typeof ReviewIndexRoute
  '/subjects': typeof SubjectsIndexRoute
  '/guides/$slug/walkthrough': typeof GuidesSlugWalkthroughRoute
  '/guides/$slug': typeof GuidesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/contribute': typeof ContributeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/objectives': typeof ObjectivesRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRouteWithChildren
  '/subjects': typeof SubjectsRouteWithChildren
  '/guides/$slug': typeof GuidesSlugRouteWithChildren
  '/objectives/$slug': typeof ObjectivesSlugRoute
  '/review/$caseId': typeof ReviewCaseIdRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
  '/guides/': typeof GuidesIndexRoute
  '/objectives/': typeof ObjectivesIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/guides/$slug/walkthrough': typeof GuidesSlugWalkthroughRoute
  '/guides/$slug/': typeof GuidesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/contribute'
    | '/forgot-password'
    | '/login'
    | '/objectives'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/review'
    | '/subjects'
    | '/guides/$slug'
    | '/objectives/$slug'
    | '/review/$caseId'
    | '/subjects/$slug'
    | '/guides/'
    | '/objectives/'
    | '/review/'
    | '/subjects/'
    | '/guides/$slug/walkthrough'
    | '/guides/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/contribute'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/objectives/$slug'
    | '/review/$caseId'
    | '/subjects/$slug'
    | '/guides'
    | '/objectives'
    | '/review'
    | '/subjects'
    | '/guides/$slug/walkthrough'
    | '/guides/$slug'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/contribute'
    | '/forgot-password'
    | '/login'
    | '/objectives'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/review'
    | '/subjects'
    | '/guides/$slug'
    | '/objectives/$slug'
    | '/review/$caseId'
    | '/subjects/$slug'
    | '/guides/'
    | '/objectives/'
    | '/review/'
    | '/subjects/'
    | '/guides/$slug/walkthrough'
    | '/guides/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  ContributeRoute: typeof ContributeRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ObjectivesRoute: typeof ObjectivesRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewRoute: typeof ReviewRouteWithChildren
  SubjectsRoute: typeof SubjectsRouteWithChildren
  GuidesSlugRoute: typeof GuidesSlugRouteWithChildren
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objectives': {
      id: '/objectives'
      path: '/objectives'
      fullPath: '/objectives'
      preLoaderRoute: typeof ObjectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof SubjectsRoute
    }
    '/review/': {
      id: '/review/'
      path: '/'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/objectives/': {
      id: '/objectives/'
      path: '/'
      fullPath: '/objectives/'
      preLoaderRoute: typeof ObjectivesIndexRouteImport
      parentRoute: typeof ObjectivesRoute
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$slug': {
      id: '/subjects/$slug'
      path: '/$slug'
      fullPath: '/subjects/$slug'
      preLoaderRoute: typeof SubjectsSlugRouteImport
      parentRoute: typeof SubjectsRoute
    }
    '/review/$caseId': {
      id: '/review/$caseId'
      path: '/$caseId'
      fullPath: '/review/$caseId'
      preLoaderRoute: typeof ReviewCaseIdRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/objectives/$slug': {
      id: '/objectives/$slug'
      path: '/$slug'
      fullPath: '/objectives/$slug'
      preLoaderRoute: typeof ObjectivesSlugRouteImport
      parentRoute: typeof ObjectivesRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug/': {
      id: '/guides/$slug/'
      path: '/'
      fullPath: '/guides/$slug/'
      preLoaderRoute: typeof GuidesSlugIndexRouteImport
      parentRoute: typeof GuidesSlugRoute
    }
    '/guides/$slug/walkthrough': {
      id: '/guides/$slug/walkthrough'
      path: '/walkthrough'
      fullPath: '/guides/$slug/walkthrough'
      preLoaderRoute: typeof GuidesSlugWalkthroughRouteImport
      parentRoute: typeof GuidesSlugRoute
    }
  }
}

interface ObjectivesRouteChildren {
  ObjectivesSlugRoute: typeof ObjectivesSlugRoute
  ObjectivesIndexRoute: typeof ObjectivesIndexRoute
}

const ObjectivesRouteChildren: ObjectivesRouteChildren = {
  ObjectivesSlugRoute: ObjectivesSlugRoute,
  ObjectivesIndexRoute: ObjectivesIndexRoute,
}

const ObjectivesRouteWithChildren = ObjectivesRoute._addFileChildren(
  ObjectivesRouteChildren,
)

interface ReviewRouteChildren {
  ReviewCaseIdRoute: typeof ReviewCaseIdRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
}

const ReviewRouteChildren: ReviewRouteChildren = {
  ReviewCaseIdRoute: ReviewCaseIdRoute,
  ReviewIndexRoute: ReviewIndexRoute,
}

const ReviewRouteWithChildren =
  ReviewRoute._addFileChildren(ReviewRouteChildren)

interface SubjectsRouteChildren {
  SubjectsSlugRoute: typeof SubjectsSlugRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
}

const SubjectsRouteChildren: SubjectsRouteChildren = {
  SubjectsSlugRoute: SubjectsSlugRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
}

const SubjectsRouteWithChildren = SubjectsRoute._addFileChildren(
  SubjectsRouteChildren,
)

interface GuidesSlugRouteChildren {
  GuidesSlugWalkthroughRoute: typeof GuidesSlugWalkthroughRoute
  GuidesSlugIndexRoute: typeof GuidesSlugIndexRoute
}

const GuidesSlugRouteChildren: GuidesSlugRouteChildren = {
  GuidesSlugWalkthroughRoute: GuidesSlugWalkthroughRoute,
  GuidesSlugIndexRoute: GuidesSlugIndexRoute,
}

const GuidesSlugRouteWithChildren = GuidesSlugRoute._addFileChildren(
  GuidesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  ContributeRoute: ContributeRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ObjectivesRoute: ObjectivesRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewRoute: ReviewRouteWithChildren,
  SubjectsRoute: SubjectsRouteWithChildren,
  GuidesSlugRoute: GuidesSlugRouteWithChildren,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
